pipeline {
    agent any
    stages {
        stage("Hello") {
            steps {
                echo "Hello World"
            }
        }
        stage("git pull") {
            steps {
                checkout([$class: "GitSCM", branches: [[name: "${branch}"]], extensions: [], userRemoteConfigs: [[credentialsId: "e2804a17-90fa-4c8c-8f30-5985b4e5bb4c", url: "http://192.168.0.110:8088/adp/adp-boot.git"]]])            }
        }
        stage("maven build") {
            steps {
                sh '''
                    mvn clean install -Dmaven.test.skip=true
                    docker images
                   '''
            }
        }
    }
    post {
        cleanup {
            deleteDir()
            dir("${workspace}@tmp") {
                deleteDir()
            }
            dir("${workspace}@script") {
                deleteDir()
            }
        }
    }
}
